# Generated by Django 6.0 on 2026-01-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
